name: Build LaTeX

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Compile Assignment 1
        uses: xu-cheng/latex-action@master
        with:
          root_file: assignment_1.tex
          working_directory: assignments/
          compiler: # optional, default is latexmk
          args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
#          extra_system_packages: # optional
      - name: Upload Assignment 1
        uses: actions/upload-artifact@v1
        with:
          name: assignment_1.pdf
          path: assignments/assignment_1.pdf